[package]
name = "snowflake-settings"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
description = "User settings and configuration for Snowflake"

[lints]
workspace = true

[dependencies]
snowflake-core = { path = "../snowflake-core" }
serde = { workspace = true }
