[package]
name = "orbit-search"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
description = "Search functionality for Orbit"

[lints]
workspace = true

[dependencies]
orbit-core = { path = "../core" }
ignore = { workspace = true }
tracing = { workspace = true }
nucleo-matcher = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
