[package]
name = "snowflake-fs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
description = "File system operations for Snowflake"

[lints]
workspace = true

[dependencies]
snowflake-core = { path = "../snowflake-core" }
tokio = { workspace = true }
