[package]
name = "snowflake-lsp"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
description = "Language Server Protocol support for Snowflake"

[lints]
workspace = true

[dependencies]
snowflake-core = { path = "../snowflake-core" }
