/**
 * Protocol Module
 * IPC protocol types and Zod validation schemas
 */

// Protocol types
export type {
  // Request types
  BridgeRequest,
  CreateSessionRequest,
  DeleteSessionRequest,
  SendMessageRequest,
  InterruptRequest,
  PermissionResponseRequest,
  SetThinkingModeRequest,
  GetThinkingModeRequest,
  SetModelRequest,
  SetPlanModeRequest,
  GetPlanModeRequest,
  SetAcceptModeRequest,
  GetAcceptModeRequest,
  IsSessionReadyRequest,
  GetSDKSessionIdRequest,
  GetStoredSessionRequest,
  CleanupSessionsRequest,
  ListAgentsRequest,
  GetAgentRequest,
  CreateAgentRequest,
  UpdateAgentRequest,
  DeleteAgentRequest,
  ListCommandsRequest,
  GetCommandRequest,
  CreateCommandRequest,
  UpdateCommandRequest,
  DeleteCommandRequest,
  ForkSessionRequest,
  RewindFilesRequest,
  ForkSessionResult,
  GenerateAgentDefinitionRequest,
  GenerateCommandDefinitionRequest,
  ShutdownRequest,
  CanvasCreateSessionRequest,
  CanvasDeleteSessionRequest,
  CanvasSendMessageRequest,
  CanvasInterruptRequest,
  CanvasToolResponseRequest,
  // Response types
  BridgeResponse,
  BridgeCommandResponse,
  SuccessResponse,
  ErrorResponse,
  BooleanResponse,
  StringResponse,
  NumberResponse,
  AgentListResponse,
  AgentResponse,
  CommandListResponse,
  CommandResponse,
  ForkSessionResponse,
  // Event types
  BridgeEvent,
  AgentMessageEvent,
  PermissionRequestEvent,
  SessionInitEventMessage,
  PlanModeChangedEvent,
  AcceptModeChangedEvent,
  ErrorEvent,
  ReadyEvent,
  CheckpointEvent,
  CanvasMessageEvent,
  CanvasToolRequestEvent,
  CanvasErrorEvent,
} from './protocol.js';

// Schemas
export { BridgeRequestSchema } from './schemas.js';
export type {
  SessionId,
  SDKSessionId,
  RequestId,
  WorkspacePath,
  AgentName,
  CommandName,
  AttachmentType,
  SubagentModel,
  SessionConfig,
  AttachmentSource,
  AttachmentContentBlock,
  SubagentDefinition,
  SlashCommandDefinition,
  PermissionResponse,
  Model,
  CommandScope,
  Decision,
} from './schemas.js';
